application: msp684
version: 1
runtime: python
api_version: 1

handlers:
- url: /task-test
  script: callsTasks.py

- url: /importtask
  script: ImportTask.py

- url: /import
  script: ImportHandler.py
  
- url: /export
  script: ExportHandler.py
  
- url: /meow
  script: meow.py
  
- url: /search
  script: Search.py
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /test.*
  script: gaeunit.py  

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /.*
  script: MainHandler.py
