application: jromeem
version: 1
runtime: python
api_version: 1

handlers:
- url: /import
  script: ImportHandler.py

- url: /meow
  script: meow.py

- url: /test.*
  script: gaeunit.py  

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /.*
  script: MainHandler.py